
<!-- This File is generated automatically by jsp2XML converter tool --> 
<!-- Written By Ramesh Mandava/Santosh Singh -->
<jsp:root
xmlns:jsp="http://java.sun.com/JSP/Page" version="1.2"
>

<jsp:text><![CDATA[<html>
<title>negativeFatalTranslationError</title>
<body>
]]></jsp:text>

<jsp:scriptlet>

<![CDATA[ /** 	Name : negativeFatalTranslationError
	Description : Here, the errorPage attribute of the page
                  directive is used.  An exception is
	              generated by dividing an integer value by 0.
                  The request is forward onto an error page where
                  the isErrorPage attribute is set to the default
                  of false.  The Error page will attempt to access
                  the implicit exception object.
	Result : A fatal translation error should occur.
**/ 
]]>

</jsp:scriptlet>

<jsp:text><![CDATA[	 
<!-- We are setting the error page to "FatalTranslationErrorPage.jsp" where isErrorPage is false -->
]]></jsp:text>
<jsp:directive.page errorPage="FatalTranslationErrorPage.jsp" autoFlush="false" />
<jsp:text><![CDATA[
]]></jsp:text>

<jsp:declaration>
<![CDATA[ int i=0; ]]>

</jsp:declaration>

<jsp:text><![CDATA[
]]></jsp:text>

<jsp:expression>
<![CDATA[ 9/i ]]>

</jsp:expression>

<jsp:text><![CDATA[
</body>
</html>
]]></jsp:text>

</jsp:root>