// Copyright 2008 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.opengse.core;

import static org.junit.Assert.fail;

import org.junit.Ignore;
import org.junit.Test;

/**
 * Unit test for {@link HttpRequestImpl}.
 *
 * @author Autogenerated.
 */
public class HttpRequestImplTest {

  @Ignore @Test
  public void testHttpRequestImpl() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testParse() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetURI() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetURI() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_getMajorVersion() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_getMinorVersion() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_getRange() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetNameFromServer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_canKeepAlive() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testPrint() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testWriteIOBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetPostBody() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_setPostBody() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_parseChunkedBody() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_isGzippedRequest() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_decodeGzippedRequest() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetInputStream() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testResetInputStream() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocale() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocales() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetCodings() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_getCharsets() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_getAcceptEncoding() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_acceptsCharset() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void test_acceptsEncoding() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetParameterMap() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testParseParameters() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetProtocol() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetReader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetConnectionInformation() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocalPort() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocalAddr() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocalName() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRemotePort() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetUserIPHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRemoteAddr() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetSocketRemoteAddr() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRemoteHost() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetScheme() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetServerName() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetServerPort() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetCharacterEncoding() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetMethod() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetPathTranslated() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetQueryString() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRequestURI() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRequestURL() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetRequestURLPrefix() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testIsSecure() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetServer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetQueryParameterSet() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeaders() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeaderNames() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetIntHeader() {
    fail("Not yet implemented");
  }

}
