// Copyright 2008 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.opengse.core;

import static org.junit.Assert.fail;

import org.junit.Ignore;
import org.junit.Test;

/**
 * Unit test for {@link HttpResponseImpl}.
 *
 * @author Autogenerated.
 */
public class HttpResponseImplTest {

  @Ignore @Test
  public void testAddHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testPrint() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testWriteIOBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testHttpResponseImpl() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetStatus() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetVersion() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetReason() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetReason() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetCompressResponse() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testCanKeepAlive() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testIsKeepAlive() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetFinished() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetPropagateOutputErrors() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetPropagateOutputErrors() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testFinish() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetCharacterEncoding() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetLocale() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetOutputBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetConnectionOutputBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetOutputStream() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetWriter() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testIsCommitted() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testReset() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testResetBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetContentLength() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetContentLength() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetActualContentLength() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetCharacterEncoding() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetContentType() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetContentType() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetLocale() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testAddCookie() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSendErrorInt() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSendErrorIntString() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetStatusInt() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetStatusIntString() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testFlushOutput() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testFlushBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetBufferSize() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetBufferSize() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testHandleConsume() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testFlushAsync() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testCanCompressForClient() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetCompressEncodingForClient() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetResolvedCookieDomain() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetSessionCookieDomain() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testOutputDefaultError() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testIsMalformedLocation() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetOutputBuffer() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetDefaultCharset() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSendStream() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testMimeHeaders() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testMimeHeadersString() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testParse() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testAddDateHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testAddIntHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testContainsHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetDateHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testSetIntHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeaders() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetHeaderNames() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testHeaderHasValue() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetDateHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testGetIntHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testRemoveHeader() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testClearHeaders() {
    fail("Not yet implemented");
  }

  @Ignore @Test
  public void testToString() {
    fail("Not yet implemented");
  }

}
