# Copyright 2008 Google Inc.  All rights reserved.
#
# Description:
#   The internal GSE being wrapped in the open-source one's filters.

java_binary(
    name = "InternalGSE",
    main_class = "com.google.opengse.examples.internalgse.Main",
    srcs = [
        "Main.java",
    ],
    deps = [
        "//third_party/java/opengse:OpenGSE",
        "//java/com/google/gse",
    ],
)
